kind: Namespace
apiVersion: v1
metadata:
  name: elastic
---
kind: Service
apiVersion: v1
metadata:
  name: es-cluster-nodeport
  namespace: elastic
spec:
  type: NodePort
  selector:
    app: es-cluster
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 32701
---
kind: Service
apiVersion: v1
metadata:
  name: es-svc
  namespace: elastic
  labels:
    app: es-cluster
  annotations:
    es.kubernetes.io/es: es-cluster
spec:
  selector:
    app: es-cluster
    role: master
  ports:
    - port: 9300
      targetPort: 9300
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: elastic
  name: es-cluster-master
  labels:
    app: es-cluster-master
    role: master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: es-cluster
      role: master
  template:
    metadata:
      labels:
        app: es-cluster
        role: master
    spec:
      containers:
        - name: elasticsearch-master
          image: registry.cn-hangzhou.aliyuncs.com/k8sos/es:v1
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "sysctl -w vm.max_map_count=262144; ulimit -l unlimited;"
          securityContext:
            privileged: true
          readinessProbe:
            httpGet:
              port: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
          env:
            - name: "cluster.name"
              value: "es-cluster"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: "discovery.zen.ping.unicast.hosts"
              value: "es-svc"
            - name: "discovery.zen.minimum_master_nodes"
              value: "2"
            - name: "discovery.zen.ping_timeout"
              value: "5s"
            - name: "node.master"
              value: "true"
            - name: "node.data"
              value: "false"
            - name: "ES_JAVA_OPTS"
              value: "-Xms256m -Xmx256m"
            - name: "http.cors.enabled"
              value: "true"
            - name: "http.cors.allow-origin"
              value: "*"
      volumes:
        - name: es-data
          emptyDir: {}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: elastic
  name: es-head
spec:
  selector:
    matchLabels:
      app: es-head
  template:
    metadata:
      labels:
        app: es-head
    spec:
      containers:
        - name: head
          image: alvinos/elasticsearch-head
          ports:
            - containerPort: 9100
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: es-head-svc
  namespace: elastic
spec:
  type: NodePort
  selector:
    app: es-head
  ports:
    - port: 9100
      targetPort: 9100
      nodePort: 32701
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: es-cluster-data-hot
  namespace: elastic
  labels:
    app: es-cluster-data-hot
    role: data
spec:
  selector:
    matchLabels:
      app: es-cluster
      role: data
      datatype: hot
  template:
    metadata:
      labels:
        app: es-cluster
        role: data
        datatype: hot
    spec:
      containers:
        - name: es-cluster-hot
          image: registry.cn-hangzhou.aliyuncs.com/k8sos/es:v1
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: "cluster.name"
              value: "es-cluster"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: "discovery.zen.ping.unicast.hosts"
              value: "es-svc"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms256m -Xmx256m"
            - name: "node.attr.box_type"
              value: "hot"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "sysctl -w vm.max_map_count=262144; ulimit -l unlimited;"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      volumes:
        - name: es-data
          emptyDir: {}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: es-cluster-data-warm
  namespace: elastic
  labels:
    app: es-cluster-data-warm
    role: data
spec:
  selector:
    matchLabels:
      app: es-cluster
      role: data
      datatype: warm
  template:
    metadata:
      labels:
        app: es-cluster
        role: data
        datatype: warm
    spec:
      containers:
        - name: es-cluster-warm
          image: registry.cn-hangzhou.aliyuncs.com/k8sos/es:v1
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: "cluster.name"
              value: "es-cluster"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: "discovery.zen.ping.unicast.hosts"
              value: "es-svc"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms256m -Xmx256m"
            - name: "node.attr.box_type"
              value: "warm"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "sysctl -w vm.max_map_count=262144; ulimit -l unlimited;"
          securityContext:
            privileged: true
          readinessProbe:
            httpGet:
              port: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      volumes:
        - name: es-data
          emptyDir: {}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: es-cluster-data-cold
  namespace: elastic
  labels:
    app: es-cluster-data-cold
    role: data
spec:
  selector:
    matchLabels:
      app: es-cluster
      role: data
      datatype: cold
  template:
    metadata:
      labels:
        app: es-cluster
        role: data
        datatype: cold
    spec:
      containers:
        - name: es-cluster-cold
          image: registry.cn-hangzhou.aliyuncs.com/k8sos/es:v1
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: "cluster.name"
              value: "es-cluster"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: "discovery.zen.ping.unicast.hosts"
              value: "es-svc"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms256m -Xmx256m"
            - name: "node.attr.box_type"
              value: "cold"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "sysctl -w vm.max_map_count=262144; ulimit -l unlimited;"
          securityContext:
            privileged: true
          readinessProbe:
            httpGet:
              port: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      volumes:
        - name: es-data
          emptyDir: {}